name: first workflow

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Echo success
              run: echo "succeed"
