name: test
on:
    push:
        branches:
            - main
            - master
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: echo_hello
              run: echo "hello from actions"
